### PR TITLE
micro-s3

### PR DESCRIPTION
**Pull request by earlzero**
Plugin simplify using AmazonS3Client. You can just set properties for accessing s3 and use provided bean.

### CODE REVIEW

**Comment by johnmcclean-aol** [comment]
Cool. We should build this out over time to add in support for manifests and transparent eventual consistency.

**Comment by marcocast** [comment]
Have a look at Jcloud (https://jclouds.apache.org/) so you could probably
design something more cloud generic and flexible (not only AWS).

On Mon, Dec 21, 2015 at 1:30 PM, johnmcclean-aol <notifications@github.com>
wrote:

> Merged #132 <https://github.com/aol/micro-server/pull/132>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aol/micro-server/pull/132#event-497381275>.
>



-- 
Marco Castigliego
------
On the web : technical blog <http://rdafbn.blogspot.co.uk/> , opensource
<http://code.google.com/p/grep4j/> , linkedin
<http://www.linkedin.com/pub/marco-castigliego/0/797/a26>

**Comment by marcocast** [comment]
Maybe have a look at Jcloud (https://jclouds.apache.org/), you could design something more cloud generic and flexible (not only AWS).

**Comment by johnmcclean-aol** [comment]
Cool - good idea Marco, this plugin can become micro-jclouds. Will create an issue for this.

**Pull request merged**
